on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  push-test:
    name: push and build test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.3.3
      
    - name: Gradle Test
      run: gradle test
      
